/*
Goblin IR Orchestrator v0.1
Author: Chris J.M. Wing
Date: 27/09/2026

Input:
	AST generated by the Goblin Parser
Output:
	Validated GoblinIR generated by the IRValidator.

Guarantees:
	- Each step of the IR process is executed in order (Reducer, Validator, later Optimiser)
	- Any errors encountered during any of these stages are captured and returned
*/

package middleware

import (
	"goblin.org/main/frontend/ast"
	i "goblin.org/main/middleware/irtypes"
)

func OrchestrateIRLayer(program ast.Program) ([]i.IRCommand, error) {

	context := i.IRContext{
		Commands:    make([]i.IRCommand, 0),
		Storage:     make([]i.IRValue, 0),
		Temporaries: make([]i.IRValue, 0),
		Labels:      make([]i.IRLabel, 0),
		Symbols:     make(map[string]i.IRAddress),
		PC:          0,
	}

	// 1. Reduce the AST down into GoblinIR.
	rawIR, err := Reduce(program, &context)
	if err != nil {
		return []i.IRCommand{}, err
	}

	PrintIR("raw ir:", rawIR)

	// 2. Validate the Raw GoblinIR into Validated GoblinIR.
	validatedIR, err := Validate(rawIR, &context)
	if err != nil {
		return []i.IRCommand{}, err
	}

	PrintIR("validated ir:", rawIR)

	return validatedIR, nil
}
